version: '3'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./:/work
    environment:
      - JUPYTER_TOKEN=toor@123

